services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    disk:
      persist: true
      mountPath: /var/data/reviews

